"""init

Revision ID: 7a10d7301ab0
Revises: 
Create Date: 2024-12-10 09:34:50.963105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a10d7301ab0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('english', sa.String(length=128), nullable=False),
    sa.Column('russian', sa.String(length=128), nullable=True),
    sa.Column('transcription', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
